name: db-dev
services:
  database:
    image: postgres
    ports:
      - "${POSTGRES_HOST}:${DATABASE_EXPOSE_PORT}:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
